-- MySQL Script generated by MySQL Workbench
-- Sun Aug 16 17:06:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TouchePasAuKlaxon_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TouchePasAuKlaxon_DB` ;

-- -----------------------------------------------------
-- Schema TouchePasAuKlaxon_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TouchePasAuKlaxon_DB` DEFAULT CHARACTER SET utf8 ;
USE `TouchePasAuKlaxon_DB` ;

-- -----------------------------------------------------
-- Table `TouchePasAuKlaxon_DB`.`agencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TouchePasAuKlaxon_DB`.`agencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TouchePasAuKlaxon_DB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TouchePasAuKlaxon_DB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL DEFAULT 'mDp1234',
  `must_change_password` TINYINT NOT NULL DEFAULT 0,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TouchePasAuKlaxon_DB`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TouchePasAuKlaxon_DB`.`trips` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departure_at` DATETIME NOT NULL,
  `arrival_at` DATETIME NOT NULL,
  `available_places` INT NOT NULL,
  `total_places` INT NOT NULL,
  `author_id` INT NOT NULL,
  `from_agency_id` INT NOT NULL,
  `to_agency_id` INT NOT NULL,
  PRIMARY KEY (`id`, `author_id`, `from_agency_id`, `to_agency_id`),
  INDEX `fk_trips_agencies_idx` (`from_agency_id` ASC) VISIBLE,
  INDEX `fk_trips_agencies1_idx` (`to_agency_id` ASC) VISIBLE,
  INDEX `fk_trips_users1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_trips_agencies`
    FOREIGN KEY (`from_agency_id`)
    REFERENCES `TouchePasAuKlaxon_DB`.`agencies` (`id`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_trips_agencies1`
    FOREIGN KEY (`to_agency_id`)
    REFERENCES `TouchePasAuKlaxon_DB`.`agencies` (`id`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_trips_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `TouchePasAuKlaxon_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
